chore(actions): fix error for check api

diff --git a/.github/workflows/build_packages.yaml b/.github/workflows/build_packages.yaml
--- a/.github/workflows/build_packages.yaml
+++ b/.github/workflows/build_packages.yaml
@@ -90,17 +90,17 @@ jobs:
             container_id=$(docker run -d emqx/kuiper:$(git describe --tags --always))
             ip_address=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $container_id)
             sleep 10
-            if [ "$(curl ${ip_address}:9081)" != "OK" ]; then echo "docker image failed"; exit 1; fi
+            if ! curl ${ip_address}:9081  >/dev/null 2>&1; then echo "docker image failed"; exit 1; fi
 
             container_id=$(docker run -d emqx/kuiper:$(git describe --tags --always)-slim)
             ip_address=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $container_id)
             sleep 10
-            if [ "$(curl ${ip_address}:9081)" != "OK" ]; then echo "docker image failed"; exit 1; fi
+            if ! curl ${ip_address}:9081  >/dev/null 2>&1; then echo "docker image failed"; exit 1; fi
 
             container_id=$(docker run -d emqx/kuiper:$(git describe --tags --always)-alpine)
             ip_address=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $container_id)
             sleep 10
-            if [ "$(curl ${ip_address}:9081)" != "OK" ]; then echo "docker image failed"; exit 1; fi
+            if ! curl ${ip_address}:9081  >/dev/null 2>&1; then echo "docker image failed"; exit 1; fi
         - name: build docker images
           if: github.event_name == 'release'
           run: |
