chore: restore plugin build
Signed-off-by: Jiyong Huang <huangjy@emqx.io>

diff --git a/.github/workflows/build_packages.yaml b/.github/workflows/build_packages.yaml
--- a/.github/workflows/build_packages.yaml
+++ b/.github/workflows/build_packages.yaml
@@ -161,6 +161,115 @@ jobs:
         labels: ${{ steps.meta.outputs.labels }}
         file: deploy/docker/Dockerfile${{ matrix.suffix }}
 
+  build-plugins:
+    runs-on: ubuntu-latest
+    needs: prepare
+
+    strategy:
+      fail-fast: false
+      matrix:
+        plugin:
+          - sinks/image
+          - sinks/influx
+          - sinks/influx2
+          - sinks/zmq
+          - sinks/kafka
+          - sinks/sql
+          - sources/random
+          - sources/zmq
+          - sources/sql
+          - sources/video
+          - sources/kafka
+          - functions/accumulateWordCount
+          - functions/countPlusOne
+          - functions/echo
+          - functions/image
+          - functions/geohash
+          - functions/labelImage
+          - functions/tfLite
+        arch: ${{fromJson(needs.prepare.outputs.arch)}}
+        os:
+          - [ debian, "slim" ]
+          - [ alpine, "alpine" ]
+        golang:
+          - 1.23.1
+        exclude:
+          - arch: linux/arm/v7
+          - os: [ alpine,"alpine" ]
+            plugin: functions/labelImage
+          - os: [ alpine,"alpine" ]
+            plugin: functions/tfLite
+
+    steps:
+      - uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
+      - uses: docker/setup-buildx-action@v3
+      - uses: docker/setup-qemu-action@v3
+        with:
+          image: tonistiigi/binfmt:latest
+          platforms: all
+      - name: build plugins
+        run: |
+          docker run -i --rm \
+              -v $(pwd):/ekuiper \
+              --workdir /ekuiper \
+              --platform ${{ matrix.arch }} \
+              ghcr.io/lf-edge/ekuiper/base:${{ matrix.golang }}-${{ matrix.os[0] }} \
+              bash -euc "git config --global --add safe.directory /ekuiper && make ${{ matrix.plugin }}"
+      - name: Build ekuiper image
+        uses: docker/build-push-action@v6
+        if: matrix.arch == 'linux/amd64'
+        with:
+          context: .
+          platforms: linux/amd64
+          push: false
+          load: true
+          tags: docker.io/lfedge/ekuiper-${{ matrix.os[0] }}
+          file: deploy/docker/Dockerfile-${{ matrix.os[1] }}
+      - name: test docker and plugins
+        if: matrix.arch == 'linux/amd64'
+        env:
+          PLUGIN: ${{ matrix.plugin }}
+        run: |
+          set -e -x -u
+          plugin_type=$(echo ${PLUGIN%%/*})
+          plugin_name=$(echo ${PLUGIN##*/})
+          
+          container_id=$(docker run -u 0 -d -v $(pwd)/_plugins:/var/plugins docker.io/lfedge/ekuiper-${{ matrix.os[0] }})
+          ip_address=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $container_id)
+          os=$(docker exec -i ${container_id} sh -c "sed -n '/^ID=/p' /etc/os-release | sed -r 's/ID=(.*)/\1/g'" )
+          sleep 5
+          if ! curl ${ip_address}:9081  >/dev/null 2>&1; then echo "docker image failed"; exit 1; fi
+          if [ "${plugin_name}" = "image" ]; then
+              curl \
+              ${ip_address}:9081/plugins/${plugin_type} \
+              -X POST \
+              -d "{\"name\":\"${plugin_name}\", \"file\":\"file:///var/plugins/${os}/${plugin_type}/${plugin_name}_amd64.zip\", \"functions\": [\"resize\",\"thumbnail\"]}"
+          elif [ "${plugin_name}" = "geohash" ]; then
+              curl \
+              ${ip_address}:9081/plugins/${plugin_type} \
+              -X POST \
+              -d "{\"name\":\"${plugin_name}\", \"file\":\"file:///var/plugins/${os}/${plugin_type}/${plugin_name}_amd64.zip\", \"functions\": [\"geohashEncode\", \"geohashEncodeInt\", \"geohashDecode\", \"geohashDecodeInt\", \"geohashBoundingBox\", \"geohashBoundingBoxInt\", \"geohashNeighbor\", \"geohashNeighborInt\", \"geohashNeighbors\", \"geohashNeighborsInt\"]}"
+          else
+              curl \
+              ${ip_address}:9081/plugins/${plugin_type} \
+              -X POST \
+              -d "{\"name\":\"${plugin_name}\", \"file\":\"file:///var/plugins/${os}/${plugin_type}/${plugin_name}_amd64.zip\"}"
+          fi
+          docker logs ${container_id}
+          [ $plugin_name = $(curl ${ip_address}:9081/plugins/${plugin_type}/${plugin_name} | jq '.name'| sed 's/\"//g' ) ] || exit 1
+      - name: Set artifact name
+        id: artifact_name
+        run: |
+          plugin_name="${{ matrix.plugin }}"
+          artifact_name="${plugin_name/\//_}"
+          echo "::set-output name=artifact_name::$artifact_name"
+      - uses: actions/upload-artifact@v4
+        with:
+          name: ${{ steps.artifact_name.outputs.artifact_name }}
+          path: _plugins/
+
   build-kubernetes-tool:
     runs-on: ubuntu-latest
 
@@ -204,6 +313,9 @@ jobs:
       with:
         username: ${{ secrets.DOCKER_HUB_USER }}
         password: ${{ secrets.DOCKER_HUB_TOKEN }}
+    - name: Update version for setup.py
+      if: github.event_name == 'release'
+      run: sed -i -r "s|([ \t]*version=).*|\1'${GITHUB_REF#refs/tags/}',|1" sdk/python/setup.py
     - name: Build multi platform image
       uses: docker/build-push-action@v6
       with:
@@ -220,6 +332,7 @@ jobs:
     needs:
     - build
     - build-on-mac
+    - build-plugins
 
     steps:
     - uses: actions/checkout@v4
@@ -231,6 +344,10 @@ jobs:
       with:
         name: mac_packages
         path: _packages
+    - uses: actions/download-artifact@v4
+      with:
+        name: plugins
+        path: _plugins
     - name: check packages
       run: |
         cd _packages && for var in $( ls |grep -v sha256); do
