chore(CI): fix "no space left" error in actions

diff --git a/.github/workflows/build_packages.yaml b/.github/workflows/build_packages.yaml
--- a/.github/workflows/build_packages.yaml
+++ b/.github/workflows/build_packages.yaml
@@ -20,7 +20,7 @@ jobs:
           run: |
             mkdir -p $HOME/.docker
             echo '{ "experimental": "enabled" }' | tee $HOME/.docker/config.json
-            echo '{ "experimental": true, "storage-driver": "overlay2", "max-concurrent-downloads": 50, "max-concurrent-uploads": 50, "graph": "/mnt/docker" }' | sudo tee /etc/docker/daemon.json
+            echo '{ "experimental": true, "storage-driver": "overlay2", "max-concurrent-downloads": 50, "max-concurrent-uploads": 50 }' | sudo tee /etc/docker/daemon.json
             sudo systemctl restart docker
             docker info
             docker buildx create --use --name mybuild
@@ -56,10 +56,46 @@ jobs:
             name: packages-mac
             path: _packages/.
 
-    build-docker-images-and-plugins:
+    build-docker-images:
         runs-on: ubuntu-latest
 
+        steps:
+        - uses: actions/checkout@v2
+          with:
+            fetch-depth: 0
+        - name: prepare docker
+          run: |
+            mkdir -p $HOME/.docker
+            echo '{ "experimental": "enabled" }' | tee $HOME/.docker/config.json
+            echo '{ "experimental": true, "storage-driver": "overlay2", "max-concurrent-downloads": 50, "max-concurrent-uploads": 50, "graph": "/mnt/docker" }' | sudo tee /etc/docker/daemon.json
+            sudo systemctl restart docker
+            docker version
+            docker buildx create --use --name mybuild
+            docker run --rm --privileged tonistiigi/binfmt --install all
+        - name: build docker image
+          run: |
+            make docker -j4
+            docker save emqx/kuiper:$(git describe --tags --always)-slim > kuiper-image.tar.gz
+        - name: test docker image
+          run: |
+            for image_id in $(docker images emqx/kuiper -q); do
+              container_id=$(docker run -d $image_id)
+              ip_address=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $container_id)
+              sleep 5
+              if ! curl ${ip_address}:9081  >/dev/null 2>&1; then echo "docker image failed"; exit 1; fi
+            done
+        - uses: actions/upload-artifact@v2
+          with:
+            name: kuiper-image
+            path: "kuiper-image.tar.gz"
+
+    build-plugins:
+        runs-on: ubuntu-latest
+
+        needs: build-docker-images
+
         strategy:
+            fail-fast: false
             matrix:
                 plugin:
                 - sinks/file
@@ -89,17 +125,21 @@ jobs:
             docker version
             docker buildx create --use --name mybuild
             docker run --rm --privileged tonistiigi/binfmt --install all
-        - name: build docker image
-          run: make docker -j4
         - name: build debian plugins
           env:
             PLUGIN: ${{ matrix.plugin }}
-          run: make ${PLUGIN}
+          run: |
+              make ${PLUGIN}
+        - uses: actions/download-artifact@v1
+          with:
+            name: kuiper-image
+            path: .
         - name: test docker and plugins
           env:
             PLUGIN: ${{ matrix.plugin }}
           run: |
             set -e -x -u
+            docker load < kuiper-image.tar.gz
             plugin_type=$(echo ${PLUGIN%%/*})
             plugin_name=$(echo ${PLUGIN##*/})
 
@@ -141,9 +181,10 @@ jobs:
 
     build-docker-manifest-images:
         runs-on: ubuntu-latest
-        
-        needs:
-        - build-docker-images-and-plugins
+
+        needs: build-docker-images
+
+        if: github.event_name == 'release'
 
         strategy:
             matrix:
@@ -156,18 +197,7 @@ jobs:
         - uses: actions/checkout@v2
           with:
             fetch-depth: 0
-        - name: install docker
-          if: github.event_name == 'release'
-          run: |
-            sudo apt-get remove docker docker-engine docker.io containerd runc
-            sudo apt-get update
-            sudo apt-get install apt-transport-https ca-certificates curl gnupg-agent software-properties-common
-            curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
-            sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
-            sudo apt-get update
-            sudo apt-get install docker-ce docker-ce-cli containerd.io jq
         - name: prepare docker
-          if: github.event_name == 'release'
           run: |
             mkdir -p $HOME/.docker
             echo '{ "experimental": "enabled" }' | tee $HOME/.docker/config.json
@@ -177,7 +207,7 @@ jobs:
             docker buildx create --use --name mybuild
             docker run --rm --privileged tonistiigi/binfmt --install all
         - name: cross build docker images
-          if: (matrix.suffix == 'fat') && (github.event_name == 'release')
+          if: matrix.suffix == 'fat'
           run: |
             set -e -u -x
             echo ${{ secrets.DOCKER_HUB_TOKEN }} | docker login -u ${{ secrets.DOCKER_HUB_USER }} --password-stdin
@@ -187,7 +217,7 @@ jobs:
             -f deploy/docker/Dockerfile . \
             --push
         - name: cross build docker images
-          if: (matrix.suffix != 'fat') && (github.event_name == 'release')
+          if: matrix.suffix != 'fat'
           env:
               SUFFIX: ${{ matrix.suffix }}
           run: |
@@ -248,7 +278,7 @@ jobs:
         needs:
         - build
         - build-on-mac
-        - build-docker-images-and-plugins
+        - build-plugins
 
         steps:
         - uses: actions/checkout@v2
