chore(CI): update build docker
Signed-off-by: zhanghongtong <rory-z@outlook.com>

diff --git a/.github/workflows/build_packages.yaml b/.github/workflows/build_packages.yaml
--- a/.github/workflows/build_packages.yaml
+++ b/.github/workflows/build_packages.yaml
@@ -93,6 +93,13 @@ jobs:
     build-docker-images:
         runs-on: ubuntu-latest
 
+        strategy:
+            matrix:
+                suffix:
+                - ""
+                - "-slim"
+                - "-alpine"
+
         steps:
         - uses: actions/checkout@v2
           with:
@@ -102,22 +109,50 @@ jobs:
           with:
             image: tonistiigi/binfmt:latest
             platforms: all
-        - name: build docker image
-          run: |
-            make docker -j4
-            docker save lfedge/ekuiper:$(git describe --tags --always)-slim > kuiper-image.tar.gz
-        - name: test docker image
-          run: |
-            for image_id in $(docker images lfedge/ekuiper -q); do
-              container_id=$(docker run -d $image_id)
-              ip_address=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $container_id)
-              sleep 5
-              if ! curl ${ip_address}:9081  >/dev/null 2>&1; then echo "docker image failed"; exit 1; fi
-            done
-        - uses: actions/upload-artifact@v2
+        - uses: docker/metadata-action@v3
+          id: meta
           with:
-            name: kuiper-image
-            path: "kuiper-image.tar.gz"
+            images: ${{ github.repository }}
+            flavor: |
+              latest=${{ github.event_name == 'release' && !github.event.release.prerelease}}
+              suffix=${{ matrix.suffix }}
+            tags: |
+              type=ref,event=branch
+              type=ref,event=pr
+              type=ref,event=tag
+              type=semver,pattern={{version}}
+              type=semver,pattern={{major}}.{{minor}}
+        - uses: docker/login-action@v1
+          if: github.event_name == 'release'
+          with:
+            username: ${{ secrets.DOCKER_HUB_USER }}
+            password: ${{ secrets.DOCKER_HUB_TOKEN }}
+        - name: Build single platform image
+          id: single_image
+          uses: docker/build-push-action@v2
+          with:
+            context: .
+            platforms: linux/amd64
+            push: false
+            load: true
+            tags: ${{ steps.meta.outputs.tags }}
+            labels: ${{ steps.meta.outputs.labels }}
+            file: deploy/docker/Dockerfile${{ matrix.suffix }}
+        - name: Test docker image
+          run: |
+            docker run -d --name ekuiper "${{ github.repository }}@${{ steps.single_image.outputs.digest }}"
+            ip_address=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' ekuiper)
+            sleep 5
+            if ! curl ${ip_address}:9081  >/dev/null 2>&1; then echo "docker image failed"; exit 1; fi
+        - name: Build multi platform image
+          uses: docker/build-push-action@v2
+          with:
+            context: .
+            platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/386
+            push: ${{ github.event_name == 'release' }}
+            tags: ${{ steps.meta.outputs.tags }}
+            labels: ${{ steps.meta.outputs.labels }}
+            file: deploy/docker/Dockerfile${{ matrix.suffix }}
 
     build-plugins:
         runs-on: ubuntu-latest
@@ -152,6 +187,15 @@ jobs:
           with:
             image: tonistiigi/binfmt:latest
             platforms: all
+        - name: Build single platform image
+          uses: docker/build-push-action@v2
+          with:
+            context: .
+            platforms: linux/amd64
+            push: false
+            load: true
+            tags: ${{ github.repository }}
+            file: deploy/docker/Dockerfile
         - name: build debian plugins
           env:
             PLUGIN: ${{ matrix.plugin }}
@@ -170,89 +214,38 @@ jobs:
             plugin_type=$(echo ${PLUGIN%%/*})
             plugin_name=$(echo ${PLUGIN##*/})
 
-            for image_id in $(docker images lfedge/ekuiper -q); do
-                container_id=$(docker run -d -v $(pwd)/_plugins:/var/plugins $image_id)
-                ip_address=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $container_id)
-                os=$(docker exec -i ${container_id} sh -c "sed -n '/^ID=/p' /etc/os-release | sed -r 's/ID=(.*)/\1/g'" )
-                sleep 5
-                if ! curl ${ip_address}:9081  >/dev/null 2>&1; then echo "docker image failed"; exit 1; fi
-                if [ ${os} = alpine ]; then continue; fi
-                if [ "${plugin_name}" = "tdengine" ]; then
-                    curl \
-                    ${ip_address}:9081/plugins/${plugin_type} \
-                    -X POST \
-                    -d "{\"name\":\"${plugin_name}\", \"file\":\"file:///var/plugins/${os}/${plugin_type}/${plugin_name}_amd64.zip\", \"shellParas\": [\"2.0.3.1\"]}"
-                elif [ "${plugin_name}" = "image" ]; then
-                     curl \
-                     ${ip_address}:9081/plugins/${plugin_type} \
-                     -X POST \
-                     -d "{\"name\":\"${plugin_name}\", \"file\":\"file:///var/plugins/${os}/${plugin_type}/${plugin_name}_amd64.zip\", \"functions\": [\"resize\",\"thumbnail\"]}"
-                elif [ "${plugin_name}" = "geohash" ]; then
-                     curl \
-                     ${ip_address}:9081/plugins/${plugin_type} \
-                     -X POST \
-                     -d "{\"name\":\"${plugin_name}\", \"file\":\"file:///var/plugins/${os}/${plugin_type}/${plugin_name}_amd64.zip\", \"functions\": [\"geohashEncode\", \"geohashEncodeInt\", \"geohashDecode\", \"geohashDecodeInt\", \"geohashBoundingBox\", \"geohashBoundingBoxInt\", \"geohashNeighbor\", \"geohashNeighborInt\", \"geohashNeighbors\", \"geohashNeighborsInt\"]}"
-                else
-                    curl \
-                    ${ip_address}:9081/plugins/${plugin_type} \
-                    -X POST \
-                    -d "{\"name\":\"${plugin_name}\", \"file\":\"file:///var/plugins/${os}/${plugin_type}/${plugin_name}_amd64.zip\"}"
-                fi
-                docker logs ${container_id}
-                [ $plugin_name = $(curl ${ip_address}:9081/plugins/${plugin_type}/${plugin_name} | jq '.name'| sed 's/\"//g' ) ] || exit 1
-            done
+            container_id=$(docker run -d -v $(pwd)/_plugins:/var/plugins ${{ github.repository }})
+            ip_address=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $container_id)
+            os=$(docker exec -i ${container_id} sh -c "sed -n '/^ID=/p' /etc/os-release | sed -r 's/ID=(.*)/\1/g'" )
+            sleep 5
+            if ! curl ${ip_address}:9081  >/dev/null 2>&1; then echo "docker image failed"; exit 1; fi
+            if [ "${plugin_name}" = "tdengine" ]; then
+                curl \
+                ${ip_address}:9081/plugins/${plugin_type} \
+                -X POST \
+                -d "{\"name\":\"${plugin_name}\", \"file\":\"file:///var/plugins/${os}/${plugin_type}/${plugin_name}_amd64.zip\", \"shellParas\": [\"2.0.3.1\"]}"
+            elif [ "${plugin_name}" = "image" ]; then
+                 curl \
+                 ${ip_address}:9081/plugins/${plugin_type} \
+                 -X POST \
+                 -d "{\"name\":\"${plugin_name}\", \"file\":\"file:///var/plugins/${os}/${plugin_type}/${plugin_name}_amd64.zip\", \"functions\": [\"resize\",\"thumbnail\"]}"
+            elif [ "${plugin_name}" = "geohash" ]; then
+                 curl \
+                 ${ip_address}:9081/plugins/${plugin_type} \
+                 -X POST \
+                 -d "{\"name\":\"${plugin_name}\", \"file\":\"file:///var/plugins/${os}/${plugin_type}/${plugin_name}_amd64.zip\", \"functions\": [\"geohashEncode\", \"geohashEncodeInt\", \"geohashDecode\", \"geohashDecodeInt\", \"geohashBoundingBox\", \"geohashBoundingBoxInt\", \"geohashNeighbor\", \"geohashNeighborInt\", \"geohashNeighbors\", \"geohashNeighborsInt\"]}"
+            else
+                curl \
+                ${ip_address}:9081/plugins/${plugin_type} \
+                -X POST \
+                -d "{\"name\":\"${plugin_name}\", \"file\":\"file:///var/plugins/${os}/${plugin_type}/${plugin_name}_amd64.zip\"}"
+            fi
+            docker logs ${container_id}
+            [ $plugin_name = $(curl ${ip_address}:9081/plugins/${plugin_type}/${plugin_name} | jq '.name'| sed 's/\"//g' ) ] || exit 1
         - uses: actions/upload-artifact@v2
           with:
             name: plugins
             path: "_plugins/"
-
-    build-docker-manifest-images:
-        runs-on: ubuntu-latest
-
-        needs: build-docker-images
-
-        if: github.event_name == 'release'
-
-        strategy:
-            matrix:
-                suffix:
-                - fat
-                - slim
-                - alpine
-
-        steps:
-        - uses: actions/checkout@v2
-          with:
-            fetch-depth: 0
-        - uses: docker/setup-buildx-action@v1
-        - uses: docker/setup-qemu-action@v1
-          with:
-            image: tonistiigi/binfmt:latest
-            platforms: all
-        - uses: docker/login-action@v1
-          with:
-            username: ${{ secrets.DOCKER_HUB_USER }}
-            password: ${{ secrets.DOCKER_HUB_TOKEN }}
-        - name: cross build docker images
-          if: matrix.suffix == 'fat'
-          run: |
-            set -e -u -x
-            docker buildx build --no-cache \
-            --platform=linux/amd64,linux/arm64,linux/arm/v7,linux/386 \
-            -t lfedge/ekuiper:$(git describe --tags --always) \
-            -f deploy/docker/Dockerfile . \
-            --push
-        - name: cross build docker images
-          if: matrix.suffix != 'fat'
-          env:
-              SUFFIX: ${{ matrix.suffix }}
-          run: |
-            set -e -u -x
-            docker buildx build --no-cache \
-            --platform=linux/amd64,linux/arm64,linux/arm/v7,linux/386 \
-            -t lfedge/ekuiper:$(git describe --tags --always)-$SUFFIX \
-            -f deploy/docker/Dockerfile-$SUFFIX . \
-            --push
 
     build-kubernetes-tool:
         runs-on: ubuntu-latest
